---
output: 
    pdf_document:
        fig_caption: yes
        number_sections: true
fontsize: 11pt
geometry: margin=1in
bibliography: References.bib
csl: harvard.csl
---

<!-- maketile -->
\begin{center}
\Large\scshape{Art Price Index} \\ 
\vspace{1em}
\large\normalfont{Laurie Binge}\footnote{Laurie is a PhD candidate at the Department of Economics of Stellenbosch University.} \\
\large\normalfont{Wimpie Boshoff}\footnote{Associate Professor at the Department of Economics of Stellenbosch University.} \\
\normalsize\textit{Stellenbosch University} \\
\normalsize\normalfont{This draft: \today} 
\end{center}

\begin{small}
This paper investigates the Business Tendency Surveys conducted by the BER. The microdata from the surveys are used to calculate indicators of business sentiment for South Africa since the early 1990s. Confidence and uncertainty indicators are calculated for four sectors surveyed by the BER, as well as for the aggregate. The indicators are then compared to measures of output, including sectoral GDP, production indices and employment. The relationships are investigated using agnostic SVARs and impulse response functions. The preliminary findings indicate that.
\vspace{0.5em}
\noindent{\textbf{JEL Classification:} X01, Z01, Z01} \\
	\noindent{\textbf{Keywords:} Hedonic Art Index}
\end{small}

\renewcommand{\thefootnote}{\arabic{footnote}}

#Introduction
This paper will examine the relationship between business sentiment and real activity in South Africa. In the context of business sentiment, the two concepts which are commonly referred to are *confidence* and *uncertainty*. Business confidence involves economic agents' perceptions of the current and expected future business climate. This is dependent on the prevailing economic environment and expectations of future prospects. Uncertainty reflects agents' inability to forecast the probability of future events occurring. It entails a lack of knowledge of the set of possible outcomes and the probability of each occurring.

The global financial crisis and subsequent Great Recession were associated with low levels of confidence and heightened uncertainty. According to the @ECB2013, the financial crisis created a climate of exceptionally low confidence and heightened uncertainty, which contributed to the subsequent recession a large extent. Even the subsequent recovery was characterised by only modest improvements in business sentiment. This has motivated an increase in research on the impact of changes in business sentiment, and especially uncertainty, on real activity. 

Macroeconomic theory postulates a causal link between confidence and economic activity, based on multiple equilibria in which self-fulfilling expectations of subjective agents generate changes in real activity. Yet the empirical evidence on the relation between confidence and economic activity is inconclusive [@Taylor2007]. Recent work suggests that changes in confidence may affect long-run output growth rather than cause short-run fluctuations [@Barsky2012]. Even if confidence measures do not hold distinct short-run information, their leading indicator properties are well-established and their timely availability has made them popular with analysts all over the world. This is also the case in South Africa, where the BER's business confidence measure is used by the SARB as a leading indicator to identify the official business cycle turning points.

The recent literature has focussed particular attention on the effects of changes in uncertainty on economic activity. While the consensus in the literature is that uncertainty rises during recessions or economic crises, the precise impact of uncertainty on the real economy, and how it differs from low levels of confidence, is less clear. @Bloom2009 suggested a "wait-and-see" effect for uncertainty shocks, which would provide a channel through which uncertainty could exogenously influence production, employment and investment, thereby driving business cycles. A number of channels have been proposed, however, through which uncertainty could potentially have negative or positive effects on growth [@Bloom2014].

This ambiguity is present in the empirical literature, which may be due to the difficulties surrounding the measurement and identification of a separate causal effects. A broad range of proxies have been used to measure uncertainty. The majority of studies have looked at macroeconomic uncertainty using volatility in the stock market, GDP, bond yields and exchange rates as proxies. The rationale is that the more volatile a series, the more difficult it is to forecast and the greater the degree of uncertainty [@Bloom2014]. In addition to volatility measures, disagreement between macroeconomic forecasters, media references to "uncertainty" and standard deviations of expectations in survey responses have been used as indicators.

Some of the recent work has suggested that increases in uncertainty may generate fluctuations in output, which would have important policy implications for issues like the appropriate size of stimulus packages in periods of heightened uncertainty. However, it is not yet clear whether uncertainty itself has an impact on the business cycle or whether it is an epiphenomenon which occurs during recessions or periods of low confidence. Hence there is a need to further examine the effect of uncertainty on the real economy. 

This paper studies the relationship between sentiment and economic activity using the Bureau for Economic Research's (BER) business tendency surveys. Although measuring economic sentiment is not a straightforward task, survey-based indicators can be helpful in discovering agents' opinions on future economic developments. Survey-based measures may include information known by the respondents but not yet reflected in aggregate economic variables. Thus, they may reveal important information about expectations, particularly regarding waves of optimism or pessimism, which may be important drivers of the business cycle. Moreover, these indicators are often available earlier (with a shorter lag) than official statistics and are usually not subject to revisions [@ECB2013]. 

The aim is to construct different measures of business sentiment based on the microdata from the BER business tendency surveys. Indicators of confidence and uncertainty are calculated at sectoral level and in the aggregate. The relationships between these sentiment indicators and economic activity over the cycle are then evaluated, using the standard agnostic econometric methods (VARs) employed elsewhere. The aim is to examine whether these survey-based measures of confidence and uncertainty have unique and distinguishable relationships with real economic activity. It may be useful to examine the impact of sector-specific sentiment indicators, where the relationships might show up more clearly than in aggregate indicators [@INIS2014].

An investigation of sentiment in the developing country context might be especially informative. Developing countries are usually characterised by higher business uncertainty than developed countries [@Bloom2014]. The South African economy has been subject to much higher levels of political and economic uncertainty than developed economies. Not only is the country an emerging market, but its tumultuous political history and the legacy of Apartheid has contributed significantly to business uncertainty. It is therefore important to confirm the existence and nature of the relationship between sentiment and economic activity in settings outside of the developed world. 

#The Concepts of Confidence and Uncertainty
Within the context of business sentiment, the two concepts which are commonly referred to are business confidence and uncertainty. @Pellissier2002 described business confidence as the *"degree of sentiment towards risk taking by business for whatever reason."* Business confidence involves the state of mind of agents regarding the current and expected future business climate. It can be interpreted a function of agents' perceptions of prevailing business conditions as well as their expectations of future events.

@Knight1921 defined uncertainty as *"people's inability to forecast the likelihood of events happening."* Uncertainty entails a lack of knowledge regarding the set of possible outcomes and the probability of each occurring (e.g. the number of coins ever produced is uncertain). This lack of knowledge makes prediction increasingly difficult and uncertainty will therefore rise during unique circumstances. According to this definition, uncertainty is distinct from the concept of risk, which describes a known probability distribution over a set of events (e.g. a coin toss). Nevertheless, researchers usually refer to a single concept of uncertainty, which is typically a stand-in for a mixture of risk and uncertainty [@Bloom2014]. 

The two concepts of confidence and uncertainty are inherently linked. Confidence could be low due to a combination of high uncertainty impairing the formation of expectations, coupled with a dissatisfaction regarding current conditions [@Hart2015]. Survey-based indicators for both are usually constructed from the first and second moments of responses to specific survey questions (often the same question).

#Confidence
##Theoretical Links
Notwithstanding the popularity of confidence indicators with analysts, the stance of the academic literature is more ambiguous. The opinions range from the view that confidence measures have an important causal role in the business cycle, to the view that they contain useful predictive information but little causal role, to the conclusion that they have no value even in forecasting [@INIS2014].

Broadly speaking, there are two contrasting approaches to the role of confidence in macroeconomics. The first view, which @Barsky2012 refer to as the "animal spirits" view, claims that independent changes in beliefs have causal effects on business cycles. This view is usually associated with consumer confidence, and the idea that a long-lasting negative consumption shock, associated with an exogenous shift in pessimism, can have a causal effect on overall aggregate demand. 

The second view, which @Barsky2012 refer to as the "information" or "news" view, suggests that confidence indicators contain information about current and future economic developments. The idea is that confidence can proxy for news that agents receive about future productivity that does not otherwise show up in econometricians' information sets. This view supposes that confidence innovations might contain predictive information when agents become aware of changes in future productivity that are independent of current productivity. Both of these views can be compatible with leading indicator properties, but only the animal spirits view would imply causality [@ECB2013].

A theoretical causal link between business confidence and fluctuations in economic activity can be found in a range of dynamic general equilibrium models that incorporate the subjective views of economic agents. These models give rise to multiple equilibria that are not determined by standard economic fundamentals and in which expectations about the future level of output can become self-fulfilling. As a result, a decline in business confidence can cause a decline in output [@Taylor2007]. In other words, changes in confidence can cause changes in real activity, independently of economic fundamentals. However, the link need not necessarily be quantitatively significant. Thus, the impact of confidence on economic activity is an empirical issue [@Taylor2007].

##Empirical Findings
There are two main challenges when it comes to empirical work on business confidence: how to construct proxies for confidence and how to measure the impact of confidence on real activity. Confidence is an elusive concept, which is difficult to define precisely or measure directly. In practice, analysts typically aggregate information from business and consumer surveys to construct proxies for confidence. These surveys typically contain a small number of qualitative questions, which can be answered quickly by respondents. Indicators are typically derived from the subjective answers to questions on past, current and expected future economic developments. The assumption is that before a specific business activity is implemented (e.g. new production plans, employment, or purchases), a certain opinion-building has taken place, which may be called "sentiment" or "confidence" [@Santero1996]. The most important advantage of these surveys is that they are usually available long before official statistical data becomes available. Moreover, they are not subject to revisions and are useful in avoiding trend and seasonality problems.   

The first issue it how to summarise or aggregate the survey responses. A very common and widely used method is to calculate so-called balances. In the context of business tendency surveys, balances are simple averages of survey responses. For most survey questions there are three reply options, such as *up*, *same*, or *down*, and balances are calculated as the difference between the percentage of positive answers and percentage of negative answers. Balances are simple to implement and understand and are considered both practical and entirely adequate for cyclical analysis [@OECD2003].[^3]

[^3]: Diffusion indices are a slight variation on balances. In the context of business tendency surveys, they indicate the degree to which the change is diffused throughout the sample. The most common way to calculate a diffusion index consists of taking the percentage of respondents answering positively and adding it to half of the percentage of respondents reporting "unchanged". Thus, diffusion indices are a linear transformation of balances and have the same information content (OECD 2003).

Although balances are by far the most common aggregation method used by statistical agencies and analysts, they do rely on assumptions about the distribution of responses. Namely, that the "unchanged" share is constant over time and that the relationship among positive and negative answers is linear and constant over time. For this reason, various alternatives have been discussed in the literature, including the probabilistic approach, the regression approach, and the latent factor approach [@INIS2014].[^4] However, these approaches usually require actual quantitative measures of the relevant variables, which is very restrictive in the case of business confidence, where actual quantitative measures are not available. Moreover, the fact that they are linked to a reference series, implies that these methods can become unreliable when exceptional events have a large impact on the correlation between the survey data and the quantitative reference data [@INIS2014].

[^4]: The probability approach assumes a probability distribution for the variable concerned, which is required to infer the parameters of the probability distribution functions. The statistic is a linear combination of values deriving from a transformation of the observed frequency of the answers. The regression approach uses the relationship between actual values (measured by official statistics) and respondents' perception of the past (reported in the business surveys as judgements) as a yardstick for the quantification of respondents' expectations about the future. Thus, quantitative expectations are a function of a specific regression model rather than a specific probability distribution (Nardo 2003). The latent factor approach regards the percentages of each qualitative answer as a function of a common "latent measure" observed by respondent but not by econometricians. We can try these, but it does not seem very useful for confidence? 

The evidence suggests that sophisticated methods tend to produce indicators that follow the common trend and cycle, which can be more easily deduced by simple aggregation methods, such as balances. For instance, the Italian National Statistical Agency found a very high correlation between balances and more sophisticated indictors when three-option replies were used [@OECD2003]. @Driver2004 assessed different ways of converting qualitative data, obtained from the UK employers' business survey, into quantitative indices for a number of economic variables. The correspondence between the observed actual values of six economic variables and the corresponding transformed survey responses was considered. They found that the balance statistic was a satisfactory method of transforming the questions on investment, output and exports.

The next issue concerns the types of questions that should be used to measure confidence, and whether combinations of indicators should be used to calculate aggregate measures. Business confidence entails the relative optimism or pessimism among firms regarding *current conditions* and expected *future developments*, with the former probably influencing the latter. The recent literature suggests a distinction between indicators of current activity and forward-looking indicators [@Bachmann2010]. 

Formally, one can define a $k$-period-ahead expectations measure of activity $(C_t^k)$ at time $t$ as: $C _t^k = E_tf(\Delta^hY_{t+k}$, where $Y_{t+k}$ is a measure of real activity (usually output) at time $t+k$ and $\Delta^hY_{t+k} = Y_{t+k} - Y_{t+k-h}$. A common definition of $f(\Delta^hY_{t+k}$ relies on an up, down, or unchanged classification: $$ f(\Delta^hY_{t+k}) = \begin{cases} -1,& \text{if } \Delta^hY_{t+k} < 0\\ 0,& \text{if } \Delta^hY_{t+k} = 0\\ 1,& \text{if } \Delta^hY_{t+k} > 0\\ \end{cases} $$
Alternatively, some confidence measures rely on a binary classification (satisfactory or unsatisfactory): $$ f(\Delta^hY_{t+k}) = \begin{cases} 1,& \text{if } \Delta^hY_{t+k} \geq a\\ 0,& \text{if } \Delta^hY_{t+k} < a\\ \end{cases} $$ where $a$ is determined by the preferences of the agent. The recent literature terms $C_t^k$ a measure of "activity" when $k=0$ or a measure of "confidence" when $k>0$.
Various confidence indices have been used in the literature. For instance, @Taylor2007 used an arithmetic average of two activity measures (based on questions on current conditions) and one confidence measure (based on a question on future conditions).[^5] @Bachmann2010 and @Bachmann2013 defined two forward-looking indices and two indices of current activity, based on the Business Outlook Survey and the German Ifo Business Climate Survey.[^6] @Barsky2012 constructed a forward-looking measure of confidence from the balance of a question on expectations over the next five years.[^7] According to this distinction the BER business confidence index, discussed in more detail below, is an index of current activity. 

[^5]: The business confidence indicator was the arithmetic average of results to the following questions: assessments of order book-levels; assessments of export order-book levels; and production expectations for the months ahead.

[^6]: The forward looking question in the BOS took the following form: *"General Business Conditions: What is your evaluation of the level of general business activity six months from now vs. [current month]: decrease, no change, increase?"* In the Ifo the question was: *"Expectations for the next three months. Our domestic production activities with respect to product XY will (without taking into account differences in the length of months or seasonal fluctuations): increase, roughly stay the same, decrease."* The question on current activity took the following form for the BOS: *"General Business Conditions: What is your evaluation of the level of general business activity [last month] vs. [current month]: decrease, no change, increase?"* And for the Ifo: *"Trends in the last month. Our domestic production activities with respect to product XY have (without taking into account differences in the length of months or seasonal fluctuations): increased, roughly stayed the same, decreased."*

[^7]: Their measure was based on the following question: *"Turning to economic conditions in the country as a whole, do you expect that over the next five years we will have mostly good times, or periods of widespread unemployment and depression, or what?"* 

The construction of aggregate indicators raises question about the appropriate weighting of the individual components. Indicators from multiple sectors, in turn derived from multiple questions, are often employed. For example, the EC conducts qualitative business surveys for five different sectors, including questions on current conditions and expectations. The aggregate confidence index (the economic sentiment index) is calculated as a weighted average (using value added shares) of sentiment in industry, services, retail trade and construction, as well as among consumers [@ECB2013]. Another example is the Ifo Business Climate indicator, which is a prominent leading indicator for the German economy. It aggregates results for the manufacturing, construction, wholesaling and retailing sectors. The replies are weighted according to the importance of the industry. It is computed as a geometric mean of the balances referring to the current business situation and the business outlook in the next six months [@INIS2014].

These survey-based indicators have performed quite well in now-casting and forecasting macroeconomic variables [@Strasser2015], although the evidence has not been unanimous. The empirical literature has often investigated the extent to which confidence indicators contain information over and above economic fundamentals. In other words, studies have investigated whether confidence measures can predict economic outcomes, after appropriate macroeconomic variables are taken into account [@INIS2014]. 

@Santero1996 explored the empirical relationship between confidence indicators and output components. They found that sentiment measures from business surveys provided valuable information for the assessment of the economic situation and for forecasting, although to varying degrees across countries. They also found that business confidence indicators were much more useful than consumer confidence indicators for economic analysis.

Many of the studies have concentrated on consumer confidence when analysing the usefulness of such indicators as predictors of economic developments [@ECB2013]. @Parigi2004 investigated the forecast performance of consumer confidence for economic activity. For certain countries in their sample the results of both in-sample and out-of-sample tests confirmed the predictive power of the consumer confidence as a leading and coincident indicator. 

@Taylor2007 looked at the ability of both confidence to forecast GDP growth over and above existing leading indicators for four European economies. They found that across countries, both consumer and business confidence indicators generally exhibited good predictive power in identifying turning points in the business cycle. For example, for the UK a 1 percentage point increase in business confidence reduced the probability of a downturn by around 4 percentage points. The inclusion of confidence indicators also reduced the forecasting error associated with quantitative estimates for two of the countries in their sample (the UK and the Netherlands).

@Barsky2012 investigated the predictive ability of consumer confidence for macroeconomic variables such as real consumption and GDP. They found that the impulse responses of consumption and income to innovations in consumer confidence measures were significant, slow-building, and permanent. They concluded that consumer confidence was not merely noise, nor simply reflections of information contained in other variables. This suggested that there is at least some truth to the "news" view of confidence. If confidence contained no news about future fundamentals and the relationship between confidence and subsequent activity reflected only "animal spirits", one would expect to see at most transitory responses of consumption and income to confidence innovations. 

The seemingly conflicting results among the empirical studies may be linked to the different sets of economic indicators used in the various forecasting models, as well as different proxies used to measure confidence. The distinction between current and forward-looking measures might also be important when evaluating this literature. The literature has often attempted to evaluate how publically-disseminated sentiment indices perform, rather than to construct appropriate proxies of sentiment from underlying data (often because the micro-data is unavailable). When the confidence index is a measure of current conditions or "activity", it might be more appropriate to evaluate the indicator's ability to capture real activity accurately, instead of predicting $\Delta Y_{t+h}$, with $h>0$.

Another possibility for the disagreement may be the use of a linear functional form to model the relationship from consumer attitudes to confidence. It may be that only abrupt shifts in consumer confidence are relevant to signal changes real activity (e.g. only below a certain threshold, or only when significantly negative) [@INIS2014]. For example, @ECB2013 found that shocks to confidence played a relatively small role, compared to shocks to other economic variables. However, there were periods during which shocks to confidence played a more important role, such as during episodes of economic tensions (financial crises or economic recessions) or during geopolitical turmoil. For the Euro Area, these thresholds were found to be asymmetric: strong decreases in consumer confidence were more important in predicting future changes in consumption than large increases. This pointed to a non-linear and asymmetric relationship between confidence and economic fluctuations. The forecasting ability of confidence indicators might be completely offset by other indicators during ordinary times, while increasing notably in the presence of unusual events. 

@Parigi2004 stressed that even if confidence indicators were just a synthesis of traditional indicators, they could still be useful for monitoring economic developments in a timely manner and for forecasting. This is because they are available earlier than official quantitative statistics and are subject only to limited revisions. The @ECB2013 also argued that the strong correlations between the confidence indicators and various economic and financial variables, imply that confidence indicators are useful in monitoring economic developments, as they are both timely and point to some leading properties with respect to official quantitative data, without necessarily implying any causal relationship. 

The BER's business confidence measure is used by the SARB as an official leading indicator of the South African business cycle. @Pellissier2002 examined the ability of two business confidence indicators in South Africa (the BER and SACOB) as business cycle indicators. The business confidence indicators were highly correlated with each other and showed signs of having leading indicator properties. Both the indicators seemed to be moving towards a coincident relationship rather than a leading one. The BER business confidence indicator displayed comparable cyclical turning point attributes. More recently, @Laubscher2014 selected time series that were the closest predictors of the official reference business cycle turning points. He found that the BER business confidence index was a useful leading indicator. 

#Uncertainty
##Theoretical Links
The theoretical literature emphasises two negative and two positive channels for uncertainty to influence growth. The largest body of theoretical literature focuses on the "real options" theory, based on @Bernanke1983. Uncertainty may have economic consequences when there is a degree of irreversibility to firms' actions. Firms may choose to temporarily delay an investment if the returns to waiting exceed the returns to investing in the present period. Agents receive new information over time, reducing uncertainty and increasing their ability to undertake the optimal investment. If the value of time, i.e. the benefit of new information, exceeds the costs associated with committing to a suboptimal project, it is rational to wait before committing to an investment [@Binding2015]. In the language of real options, the option value of waiting increases as the uncertainty increases [@Bloom2014]. 

This theory has given rise to the idea of the "wait-and-see" effect [@Bloom2009]. If a firm faces large fixed adjustment costs[^8], higher uncertainty over future demand makes new hiring and investment less attractive. Firm try to minimise the number of times this fixed adjustment cost must be paid. If the future is very uncertain, in the sense that demand could be either very high or low relative to the present, then it makes sense to wait until the uncertainty is resolved [@Bachmann2010]. In other words, facing a more uncertain environment, firms pause hiring and investment, i.e. they "wait and see" how the future unfolds, which leads to a decrease in economic activity. As the future unfolds, there is pent-up demand for labour and capital. Firms are closer to their adjustment triggers in subsequent periods, leading to a rebound and even overshoot in economic activity, followed by a return to the steady state [@Bachmann2010]. Thus, the initial "bust" is followed by a quick pick-up and overshoot in economic activity [@Bachmann2013]. This provides a channel through which uncertainty shocks can exogenously influence economic activity.

[^8]: In the context of capital, these costs can have both a physical element (equipment may get damaged in installation and removal) and a financial element (the used-good discount on resale). In the context of labour, adjustment costs include recruitment, training, severance pay, as well as search frictions.

Uncertainty can also negatively affect economic activity through risk aversion and risk premia. Greater uncertainty increases risk premia if investors are risk averse by increasing the probability of default among lenders (expanding the size of the left-tail default outcomes) [@Redl2015]. This increase in borrowing costs can reduce growth, emphasised in papers on the impact of uncertainty under financial constraints [summarised in @Bloom2014 and @Bachmann2013]. Another mechanism related to risk premia is the confidence effect of uncertainty. In models where consumers have pessimistic beliefs, agents are so uncertain about the future they cannot form a probability distribution. Instead they have a range of possible outcomes and act as if the worst outcomes will occur, displaying a behaviour known as "ambiguity aversion." As the range of possible outcomes (uncertainty) expands, the worst possible outcome becomes worse, so agents cut back on investment and hiring. If agents are optimistic (they assume the best case), then uncertainty can actually have a positive impact [@Bloom2014]. 

@Bloom2014 also refers to two channels through which it can have a positive effect on economic activity. The "growth options" argument is based on the idea that uncertainty can encourage investment if it increases the size of the potential prize. This is due to the potential for an increase in upside gains, while the downside loss is limited to initial sunk costs, which leads to an increase in the expected profits from an investment. Thus uncertainty creates call option effects [@Redl2015]. 

The Oi-Hartman-Abel effect highlights the possibility that firms may be risk-loving if they can expand to exploit good outcomes and contract to insure against bad outcomes. For example, if a firm can easily halve production volumes in response to a price decrease, and double production if prices increase, it should desire a mean-preserving increase in uncertainty because it receives 50% during bad outcomes and 200% during good outcomes. In effect, the firm is partly insured against bad outcomes by being able to contract and has the option to increase its advantage from good outcomes by being able to expand. However, for this mechanism to work, firms need to be able to easily expand or contract in response to good or bad news. @Bloom2014 argues that this effect is typically not very strong in the short run because of adjustment costs, but may be more powerful in the medium to long run.

Thus, the theoretical effects of uncertainty are ambiguous, which is reflected in the empirical literature. @Bonciani2015 argues that in a general equilibrium framework the aforementioned effects may or may not be completely offset. In a New Keynesian Model, for instance, the monetary authority can partially offset the negative effects of uncertainty by reducing the nominal interest rate. They argue that this is the most important reason why many papers do not find a strong effect. However, when the monetary authority is constrained by the zero lower bound, or when there is imperfect pass-through, the effects of uncertainty become much more significant, as the central bank cannot perfectly respond to the shock. 




